export const API_CONFIG = {
  WS_URL: process.env.REACT_APP_WS_URL || 'ws://localhost:8080',
  RECONNECT_INTERVAL: 3000,
  MAX_RETRIES: 5,
  MESSAGE_TIMEOUT: 5000,
};

export const UI_CONFIG = {
  MESSAGE_PAGE_SIZE: 50,
  MAX_USERNAME_LENGTH: 20,
  MIN_USERNAME_LENGTH: 2,
  MAX_MESSAGE_LENGTH: 500,
};

export const NOTIFICATION_CONFIG = {
  DURATION: 3000,
  ANIMATION_DURATION: 300,
};
